version: '3'
services:
    app:
        container_name: php
        build:
            context: ./php
            dockerfile: Dockerfile
        tty: true
        volumes:
            - ${PWD}:/var/www/html
        ports:
            - "80:80"
        network_mode: "php_mysql_network"

    db1:
        container_name: mysql
        build:
            context: ./mysql
            dockerfile: Dockerfile
        environment:
            - MYSQL_ROOT_PASSWORD=pass
        volumes:
            # - ./mysql/mysql_conf:/etc/mysql
            - ./mysql/mysql_customconf:/etc/mysql/conf.d
            - ./mysql/mysql_data:/var/lib/mysql
            - ./mysql/mysql_backup:/var/backups
        network_mode: "php_mysql_network"

networks:
    php_mysql_network: