# Generated by Django 3.2.6 on 2021-09-06 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micropost', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, validators=[django.core.validators.RegexValidator('^[\\w+\\-.]+@[a-zA-Z\\d\\-.]+\\.[a-zA-Z]+$', 'メールアドレスの形式ではない')], verbose_name='email'),
        ),
    ]
