version: '3'
 
services:
  db:
    image: postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./micropost_app:/code
    ports:
      - "8000:8000"
    environment:
        DB_USER: postgres
        DB_PASSWORD: postgres
    depends_on:
      - db